spring.application.name=springChatbot

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# mariadb local setting
# spring.datasource.url=jdbc:mariadb://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
# mariadb server host setting
# spring.datasource.url=jdbc:mariadb://localhost:3308/test?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
# mariadb docker setting
spring.datasource.url=jdbc:mariadb://mariadb:3306/test?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul

spring.datasource.username=root
spring.datasource.password=1111
server.port=8080

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# mapper.xml ê²½ë¡ ì§ì 
mybatis.mapper-locations= mapper/**/*.xml


# file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=c:\\Temp/upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

